(defun color-theme-inkpot ()
  (interactive)
  (color-theme-install
   '(color-theme-inkpot
     ((background-color . "#1e1e27")
      (background-mode . light)
      (border-color . "#3e3e5e")
      (cursor-color . "#a81b00")
      (foreground-color . "#cfbfad")
      (mouse-color . "black"))
     (fringe ((t (:background "#3e3e5e"))))
     (mode-line ((t (:foreground "#ffffff" :background "#323232"))))
     (region ((t (:background "#404040"))))
     (font-lock-builtin-face ((t (:foreground "#c080d0"))))
     (font-lock-comment-face ((t (:foreground "#708090"))))
     (font-lock-function-name-face ((t (:foreground "#87cefa"))))
     (font-lock-keyword-face ((t (:foreground "#ffffff"))))
     (font-lock-string-face ((t (:foreground "#ffcd8b"))))
     (font-lock-type-face ((t (:foreground"#ffffff"))))
     (font-lock-constant-face ((t (:foreground "#506dbd"))))
     (font-lock-variable-name-face ((t (:foreground "#ffffff"))))
     (minibuffer-prompt ((t (:foreground "#ffffff" :bold t))))
     (font-lock-warning-face ((t (:foreground "red" :bold t))))
     )))
(provide 'color-theme-inkpot)
